name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go mod tidy

    - name: makedir
      run: mkdir build
      
    - name: Build
      run: |
        export CGO_ENABLED=0 
        export GOOS=linux
        export GOARCH=amd64 
        go build -v -o ./build/bomb_linux_x64
        export GOOS=linux
        export GOARCH=arm 
        go build -v -o ./build/bomb_linux_arm
        export GOOS=windows
        export GOARCH=arm 
        go build -v -o ./build/bomb_win_arm
        export GOOS=windows
        export GOARCH=amd64 
        go build -v -o ./build/bomb_win_x64

    - name: list
      run: ls ./build
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.4
      with:    
        path: build/
        
    - name: Release
      uses: fnkr/github-action-ghr@v1         
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GHR_COMPRESS: zip
        GHR_PATH: build/
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
